### ISSUE TITLE
A single frame in play mode

### ISSUE THREAD

**Issue by samiulextreem** [ray075hl/PPO_super_mario#2]
i tried to run your model with the command python3 run.py play mario_10000-best.dat  but all a got a flash of mario emulator and a single output 
Take Action: 	 ['right', 'B']
then the script end.

**Comment by ray075hl** [comment]
@samiulextreem  Sorry about that. Because gym_super_mario_bros library changed. Now codes have been modified to run normally, you can try it.  If you have other problem, contact me anytime at here or sent me a email.
